version: '3.6'

services:

  redis:
    image: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--maxclients 65000"]
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  worker:
    build: 
      context: .
      dockerfile: Dockerfile-worker
    depends_on:
      - redis
      - zookeeper
      - kafka
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
  monitor:
    build:
      context: .
      dockerfile: Dockerfile-monitor
    depends_on:
      - redis
      - zookeeper
      - kafka
