FROM python:3.7
RUN pip install pipenv

WORKDIR /worker
COPY . /worker/
RUN apt-get update
RUN apt-get -y install libmagickwand-dev
RUN pipenv install
ENV PYTHONUNBUFFERED 1
CMD PYTHONPATH=. pipenv run python worker/scheduler.py
